"""
Copper Miners watchlist.
Edited via TBD Technologies watchlist manager.
"""

COPPER_MINERS_GROUPS = [
    ("Bigger", [
        ("FCX", "FCX", "stock"),
        ("SCCO", "SCCO", "stock"),
        ("TECK", "TECK", "stock"),
        ("HBM", "HBM", "stock"),
        ("ERO", "ERO", "stock"),
        ("CPER", "CPER", "stock"),
        ("FM", "FM", "stock"),
        ("ARIS", "ARIS", "stock"),
        ("TGB", "TGB", "stock"),
        ("IVPAF", "IVPAF", "stock"),
        ("CS", "CS", "stock"),
        ("NEXA", "NEXA", "stock"),
        ("BVN", "BVN", "stock"),
        ("LUNMF", "LUNMF", "stock"),
        ("FILO", "FILO", "stock"),
        ("SWC", "SWC", "stock"),
        ("WPM", "WPM", "stock"),
        ("NOVR", "NOVR", "stock"),
        ("CENX", "CENX", "stock"),
        ("GLNCY", "GLNCY", "stock"),
        ("BHPG", "BHPG", "stock"),
        ("RIO", "RIO", "stock"),
        ("VALE", "VALE", "stock"),
        ("AA", "AA", "stock"),
        ("VEDL", "VEDL", "stock"),
        ("GMEXICO", "GMEXICO", "stock"),
        ("ANFGF", "ANFGF", "stock"),
        ("CSCCF", "CSCCF", "stock"),
        ("OSK", "OSK", "stock"),
        ("LNDC", "LNDC", "stock"),
        ("TLOFF", "TLOFF", "stock"),
        ("SBSW", "SBSW", "stock"),
        ("ECVTF", "ECVTF", "stock"),
        ("KGHPF", "KGHPF", "stock"),
        ("AUMN", "AUMN", "stock"),
        ("CPPMF", "CPPMF", "stock"),
        ("FTSSF", "FTSSF", "stock"),
        ("NGD", "NGD", "stock"),
        ("SOLDF", "SOLDF", "stock"),
        ("TRQ", "TRQ", "stock"),
        ("IVNHF", "IVNHF", "stock"),
        ("AMZGF", "AMZGF", "stock"),
        ("FLMMF", "FLMMF", "stock"),
        ("CSFFF", "CSFFF", "stock"),
        ("CUCO", "CUCO", "stock"),
        ("MLYF", "MLYF", "stock"),
        ("FQVLF", "FQVLF", "stock"),
        ("LBCMF", "LBCMF", "stock"),
        ("NMTLF", "NMTLF", "stock"),
        ("HUDBF", "HUDBF", "stock"),
        ("TSRMF", "TSRMF", "stock"),
        ("CPPKF", "CPPKF", "stock"),
        ("AVDGF", "AVDGF", "stock"),
        ("RGLSF", "RGLSF", "stock"),
        ("TEUTF", "TEUTF", "stock"),
        ("HNCKF", "HNCKF", "stock"),
        ("GBRRF", "GBRRF", "stock"),
        ("MEXXF", "MEXXF", "stock"),
        ("CXOXF", "CXOXF", "stock"),
        ("NGPHF", "NGPHF", "stock"),
        ("ENTEF", "ENTEF", "stock"),
    ]),
    ("Smaller", [
        ("CTPZF", "CTPZF", "stock"),
        ("SMRZF", "SMRZF", "stock"),
        ("MNRLF", "MNRLF", "stock"),
        ("REEMF", "REEMF", "stock"),
        ("NCPCF", "NCPCF", "stock"),
        ("SEMAFO", "SEMAFO", "stock"),
        ("PEMIF", "PEMIF", "stock"),
        ("KBLT", "KBLT", "stock"),
        ("CMMC", "CMMC", "stock"),
        ("HASMF", "HASMF", "stock"),
        ("CRML", "CRML", "stock"),
        ("TLRS", "TLRS", "stock"),
        ("ATUSF", "ATUSF", "stock"),
        ("GBGDF", "GBGDF", "stock"),
        ("GLDN", "GLDN", "stock"),
        ("SXOOF", "SXOOF", "stock"),
    ]),
    ("Focus", [
        ("FCX", "FCX", "stock"),
        ("SCCO", "SCCO", "stock"),
        ("TECK", "TECK", "stock"),
        ("HBM", "HBM", "stock"),
        ("ERO", "ERO", "stock"),
        ("TGB", "TGB", "stock"),
        ("BVN", "BVN", "stock"),
        ("NEXA", "NEXA", "stock"),
        ("TRQ", "TRQ", "stock"),
        ("RIO", "RIO", "stock"),
        ("VALE", "VALE", "stock"),
        ("BHP", "BHP", "stock"),
    ]),
]
