"""
ETF watchlist.
Core list of ETFs for dark pool sweep tracking and analysis.
Based on overview watchlist with additions for leveraged, crypto, and thematic coverage.
"""

ETF_GROUPS = [
    ("Broad Market", [
        ("SPY", "SPY", "stock"),
        ("QQQ", "QQQ", "stock"),
        ("IWM", "IWM", "stock"),
        ("DIA", "DIA", "stock"),
        ("MDY", "MDY", "stock"),
        ("VOO", "VOO", "stock"),
        ("VTI", "VTI", "stock"),
        ("IVV", "IVV", "stock"),
        ("RSP", "RSP", "stock"),
    ]),
    ("US Sectors", [
        ("XLK", "XLK", "stock"),
        ("XLF", "XLF", "stock"),
        ("XLE", "XLE", "stock"),
        ("XLV", "XLV", "stock"),
        ("XLI", "XLI", "stock"),
        ("XLY", "XLY", "stock"),
        ("XLP", "XLP", "stock"),
        ("XLC", "XLC", "stock"),
        ("XLB", "XLB", "stock"),
        ("XLRE", "XLRE", "stock"),
        ("XLU", "XLU", "stock"),
    ]),
    ("Thematic", [
        ("SMH", "SMH", "stock"),
        ("SOXX", "SOXX", "stock"),
        ("XBI", "XBI", "stock"),
        ("ARKK", "ARKK", "stock"),
        ("KWEB", "KWEB", "stock"),
        ("TAN", "TAN", "stock"),
        ("HACK", "HACK", "stock"),
        ("JETS", "JETS", "stock"),
        ("XHB", "XHB", "stock"),
        ("KRE", "KRE", "stock"),
    ]),
    ("Fixed Income", [
        ("TLT", "TLT", "stock"),
        ("IEF", "IEF", "stock"),
        ("SHY", "SHY", "stock"),
        ("AGG", "AGG", "stock"),
        ("BND", "BND", "stock"),
        ("HYG", "HYG", "stock"),
        ("JNK", "JNK", "stock"),
        ("LQD", "LQD", "stock"),
        ("TIP", "TIP", "stock"),
        ("TBT", "TBT", "stock"),
    ]),
    ("Developed Markets", [
        ("EWU", "EWU", "stock"),
        ("EWG", "EWG", "stock"),
        ("EWQ", "EWQ", "stock"),
        ("EWI", "EWI", "stock"),
        ("EWP", "EWP", "stock"),
        ("EWL", "EWL", "stock"),
        ("EWJ", "EWJ", "stock"),
        ("EWA", "EWA", "stock"),
        ("EWC", "EWC", "stock"),
    ]),
    ("Emerging Markets", [
        ("EEM", "EEM", "stock"),
        ("FXI", "FXI", "stock"),
        ("INDA", "INDA", "stock"),
        ("EWZ", "EWZ", "stock"),
        ("EWW", "EWW", "stock"),
        ("ECH", "ECH", "stock"),
        ("EWY", "EWY", "stock"),
        ("EWT", "EWT", "stock"),
        ("THD", "THD", "stock"),
        ("EIDO", "EIDO", "stock"),
        ("EZA", "EZA", "stock"),
        ("TUR", "TUR", "stock"),
        ("EPOL", "EPOL", "stock"),
        ("KSA", "KSA", "stock"),
    ]),
    ("Commodities", [
        ("GLD", "GLD", "stock"),
        ("SLV", "SLV", "stock"),
        ("IAU", "IAU", "stock"),
        ("GDX", "GDX", "stock"),
        ("GDXJ", "GDXJ", "stock"),
        ("USO", "USO", "stock"),
        ("UNG", "UNG", "stock"),
        ("CPER", "CPER", "stock"),
        ("DBA", "DBA", "stock"),
        ("URA", "URA", "stock"),
        ("PDBC", "PDBC", "stock"),
    ]),
    ("Leveraged", [
        ("TQQQ", "TQQQ", "stock"),
        ("SQQQ", "SQQQ", "stock"),
        ("SPXL", "SPXL", "stock"),
        ("SPXS", "SPXS", "stock"),
        ("SOXL", "SOXL", "stock"),
        ("SOXS", "SOXS", "stock"),
        ("UPRO", "UPRO", "stock"),
        ("SPXU", "SPXU", "stock"),
        ("LABU", "LABU", "stock"),
        ("LABD", "LABD", "stock"),
        ("TNA", "TNA", "stock"),
        ("FNGU", "FNGU", "stock"),
    ]),
    ("Crypto", [
        ("IBIT", "IBIT", "stock"),
        ("GBTC", "GBTC", "stock"),
        ("BITO", "BITO", "stock"),
        ("ETHE", "ETHE", "stock"),
    ]),
    ("Volatility", [
        ("VIXY", "VIXY", "stock"),
        ("VXX", "VXX", "stock"),
        ("UVXY", "UVXY", "stock"),
        ("SVXY", "SVXY", "stock"),
    ]),
    ("Currency ETFs", [
        ("UUP", "UUP", "stock"),
        ("FXE", "FXE", "stock"),
        ("FXY", "FXY", "stock"),
        ("FXB", "FXB", "stock"),
    ]),
]
