"""
Favourites watchlist.
Curated selection of top names across every major theme/sector.
Updated 2026-03-09.
"""

FAVOURITES_GROUPS = [
    ("MAG7 & Big Tech", [
        ("AAPL", "AAPL", "stock"),
        ("AMZN", "AMZN", "stock"),
        ("GOOG", "GOOG", "stock"),
        ("GOOGL", "GOOGL", "stock"),
        ("META", "META", "stock"),
        ("MSFT", "MSFT", "stock"),
        ("NVDA", "NVDA", "stock"),
        ("TSLA", "TSLA", "stock"),
    ]),
    ("AI & Semiconductors", [
        ("ADI", "ADI", "stock"),
        ("AMD", "AMD", "stock"),
        ("AMAT", "AMAT", "stock"),
        ("ARM", "ARM", "stock"),
        ("AVGO", "AVGO", "stock"),
        ("CDNS", "CDNS", "stock"),
        ("INTC", "INTC", "stock"),
        ("KLAC", "KLAC", "stock"),
        ("LRCX", "LRCX", "stock"),
        ("MPWR", "MPWR", "stock"),
        ("MRVL", "MRVL", "stock"),
        ("MU", "MU", "stock"),
        ("NXPI", "NXPI", "stock"),
        ("ON", "ON", "stock"),
        ("QCOM", "QCOM", "stock"),
        ("SMCI", "SMCI", "stock"),
        ("SNPS", "SNPS", "stock"),
        ("TSM", "TSM", "stock"),
        ("TXN", "TXN", "stock"),
    ]),
    ("AI Infrastructure & Data Centers", [
        ("CIEN", "CIEN", "stock"),
        ("COHR", "COHR", "stock"),
        ("CRDO", "CRDO", "stock"),
        ("DELL", "DELL", "stock"),
        ("DLR", "DLR", "stock"),
        ("EQIX", "EQIX", "stock"),
        ("GEV", "GEV", "stock"),
        ("GLW", "GLW", "stock"),
        ("LITE", "LITE", "stock"),
        ("VRT", "VRT", "stock"),
    ]),
    ("Cloud & Software", [
        ("ADBE", "ADBE", "stock"),
        ("APP", "APP", "stock"),
        ("CRM", "CRM", "stock"),
        ("DDOG", "DDOG", "stock"),
        ("HUBS", "HUBS", "stock"),
        ("INTU", "INTU", "stock"),
        ("MDB", "MDB", "stock"),
        ("NOW", "NOW", "stock"),
        ("ORCL", "ORCL", "stock"),
        ("PLTR", "PLTR", "stock"),
        ("SNOW", "SNOW", "stock"),
        ("TTD", "TTD", "stock"),
        ("WDAY", "WDAY", "stock"),
    ]),
    ("Cybersecurity", [
        ("CRWD", "CRWD", "stock"),
        ("FTNT", "FTNT", "stock"),
        ("NET", "NET", "stock"),
        ("PANW", "PANW", "stock"),
        ("QLYS", "QLYS", "stock"),
        ("S", "S", "stock"),
        ("ZS", "ZS", "stock"),
    ]),
    ("Crypto & Bitcoin Mining", [
        ("BITF", "BITF", "stock"),
        ("CIFR", "CIFR", "stock"),
        ("CLSK", "CLSK", "stock"),
        ("COIN", "COIN", "stock"),
        ("HUT", "HUT", "stock"),
        ("IREN", "IREN", "stock"),
        ("MARA", "MARA", "stock"),
        ("MSTR", "MSTR", "stock"),
        ("RIOT", "RIOT", "stock"),
    ]),
    ("Space & Defense", [
        ("ASTS", "ASTS", "stock"),
        ("BA", "BA", "stock"),
        ("GD", "GD", "stock"),
        ("HII", "HII", "stock"),
        ("LMT", "LMT", "stock"),
        ("LUNR", "LUNR", "stock"),
        ("NOC", "NOC", "stock"),
        ("RKLB", "RKLB", "stock"),
        ("RTX", "RTX", "stock"),
    ]),
    ("Banks & Financials", [
        ("APO", "APO", "stock"),
        ("BAC", "BAC", "stock"),
        ("BLK", "BLK", "stock"),
        ("BX", "BX", "stock"),
        ("C", "C", "stock"),
        ("COF", "COF", "stock"),
        ("GS", "GS", "stock"),
        ("HOOD", "HOOD", "stock"),
        ("IBKR", "IBKR", "stock"),
        ("JPM", "JPM", "stock"),
        ("KKR", "KKR", "stock"),
        ("MS", "MS", "stock"),
        ("SCHW", "SCHW", "stock"),
        ("WFC", "WFC", "stock"),
    ]),
    ("Fintech & Payments", [
        ("AFRM", "AFRM", "stock"),
        ("FIS", "FIS", "stock"),
        ("FISV", "FISV", "stock"),
        ("GPN", "GPN", "stock"),
        ("MA", "MA", "stock"),
        ("PYPL", "PYPL", "stock"),
        ("SQ", "SQ", "stock"),
        ("SOFI", "SOFI", "stock"),
        ("V", "V", "stock"),
    ]),
    ("Consumer & Retail", [
        ("ABNB", "ABNB", "stock"),
        ("BKNG", "BKNG", "stock"),
        ("CMG", "CMG", "stock"),
        ("COST", "COST", "stock"),
        ("CVNA", "CVNA", "stock"),
        ("DASH", "DASH", "stock"),
        ("DPZ", "DPZ", "stock"),
        ("HD", "HD", "stock"),
        ("LOW", "LOW", "stock"),
        ("LULU", "LULU", "stock"),
        ("MCD", "MCD", "stock"),
        ("NKE", "NKE", "stock"),
        ("ORLY", "ORLY", "stock"),
        ("RCL", "RCL", "stock"),
        ("SBUX", "SBUX", "stock"),
        ("TGT", "TGT", "stock"),
        ("TJX", "TJX", "stock"),
        ("UBER", "UBER", "stock"),
        ("WMT", "WMT", "stock"),
    ]),
    ("Media & Streaming", [
        ("DIS", "DIS", "stock"),
        ("NFLX", "NFLX", "stock"),
        ("ROKU", "ROKU", "stock"),
        ("SPOT", "SPOT", "stock"),
        ("WBD", "WBD", "stock"),
    ]),
    ("Healthcare & Biotech", [
        ("ABBV", "ABBV", "stock"),
        ("AMGN", "AMGN", "stock"),
        ("BMY", "BMY", "stock"),
        ("DXCM", "DXCM", "stock"),
        ("GILD", "GILD", "stock"),
        ("ISRG", "ISRG", "stock"),
        ("JNJ", "JNJ", "stock"),
        ("LLY", "LLY", "stock"),
        ("MRK", "MRK", "stock"),
        ("MRNA", "MRNA", "stock"),
        ("PFE", "PFE", "stock"),
        ("REGN", "REGN", "stock"),
        ("SYK", "SYK", "stock"),
        ("TMO", "TMO", "stock"),
        ("UNH", "UNH", "stock"),
        ("VRTX", "VRTX", "stock"),
    ]),
    ("Defensives & Staples", [
        ("CL", "CL", "stock"),
        ("KO", "KO", "stock"),
        ("MDLZ", "MDLZ", "stock"),
        ("MO", "MO", "stock"),
        ("PEP", "PEP", "stock"),
        ("PG", "PG", "stock"),
        ("PM", "PM", "stock"),
        ("WMT", "WMT", "stock"),
    ]),
    ("Energy & Oil", [
        ("COP", "COP", "stock"),
        ("CVX", "CVX", "stock"),
        ("DVN", "DVN", "stock"),
        ("EOG", "EOG", "stock"),
        ("FANG", "FANG", "stock"),
        ("MPC", "MPC", "stock"),
        ("OXY", "OXY", "stock"),
        ("SLB", "SLB", "stock"),
        ("XOM", "XOM", "stock"),
    ]),
    ("Industrials", [
        ("CAT", "CAT", "stock"),
        ("DE", "DE", "stock"),
        ("ETN", "ETN", "stock"),
        ("FDX", "FDX", "stock"),
        ("GE", "GE", "stock"),
        ("HON", "HON", "stock"),
        ("UNP", "UNP", "stock"),
        ("UPS", "UPS", "stock"),
        ("URI", "URI", "stock"),
    ]),
    ("Materials & Mining", [
        ("ALB", "ALB", "stock"),
        ("APD", "APD", "stock"),
        ("FCX", "FCX", "stock"),
        ("LIN", "LIN", "stock"),
        ("NEM", "NEM", "stock"),
        ("NUE", "NUE", "stock"),
        ("SHW", "SHW", "stock"),
        ("STLD", "STLD", "stock"),
    ]),
    ("Utilities & Nuclear", [
        ("CEG", "CEG", "stock"),
        ("NEE", "NEE", "stock"),
        ("NRG", "NRG", "stock"),
        ("SO", "SO", "stock"),
        ("VST", "VST", "stock"),
    ]),
    ("EV & Clean Energy", [
        ("CHPT", "CHPT", "stock"),
        ("ENPH", "ENPH", "stock"),
        ("FSLR", "FSLR", "stock"),
        ("LCID", "LCID", "stock"),
        ("LI", "LI", "stock"),
        ("NIO", "NIO", "stock"),
        ("PLUG", "PLUG", "stock"),
        ("RIVN", "RIVN", "stock"),
        ("XPEV", "XPEV", "stock"),
    ]),
]
