"""
Overview watchlist.
Edited via TBD Technologies watchlist manager.
"""

OVERVIEW_GROUPS = [
    ("Core US Indexes", [
        ("SPY", "SPY", "stock"),
        ("QQQ", "QQQ", "stock"),
        ("IWM", "IWM", "stock"),
        ("MDY", "MDY", "stock"),
        ("DIA", "DIA", "stock"),
    ]),
    ("US Sectors", [
        ("XLK", "XLK", "stock"),
        ("XLF", "XLF", "stock"),
        ("XLE", "XLE", "stock"),
        ("XLV", "XLV", "stock"),
        ("XLI", "XLI", "stock"),
        ("XLY", "XLY", "stock"),
        ("XLP", "XLP", "stock"),
        ("XLC", "XLC", "stock"),
        ("XLB", "XLB", "stock"),
        ("XLRE", "XLRE", "stock"),
        ("XLU", "XLU", "stock"),
    ]),
    ("Thematic", [
        ("SMH", "SMH", "stock"),
        ("XBI", "XBI", "stock"),
        ("ARKK", "ARKK", "stock"),
        ("TAN", "TAN", "stock"),
        ("HACK", "HACK", "stock"),
        ("JETS", "JETS", "stock"),
        ("XHB", "XHB", "stock"),
        ("KRE", "KRE", "stock"),
    ]),
    ("Fixed Income", [
        ("TLT", "TLT", "stock"),
        ("IEF", "IEF", "stock"),
        ("SHY", "SHY", "stock"),
        ("HYG", "HYG", "stock"),
        ("LQD", "LQD", "stock"),
        ("TIP", "TIP", "stock"),
    ]),
    ("Developed Markets", [
        ("EWU", "EWU", "stock"),
        ("EWG", "EWG", "stock"),
        ("EWQ", "EWQ", "stock"),
        ("EWI", "EWI", "stock"),
        ("EWP", "EWP", "stock"),
        ("EWL", "EWL", "stock"),
        ("EWJ", "EWJ", "stock"),
        ("EWA", "EWA", "stock"),
        ("EWC", "EWC", "stock"),
    ]),
    ("Emerging Markets", [
        ("EEM", "EEM", "stock"),
        ("FXI", "FXI", "stock"),
        ("INDA", "INDA", "stock"),
        ("EWZ", "EWZ", "stock"),
        ("EWW", "EWW", "stock"),
        ("ECH", "ECH", "stock"),
        ("EWY", "EWY", "stock"),
        ("EWT", "EWT", "stock"),
        ("THD", "THD", "stock"),
        ("EIDO", "EIDO", "stock"),
        ("EZA", "EZA", "stock"),
        ("TUR", "TUR", "stock"),
        ("EPOL", "EPOL", "stock"),
        ("KSA", "KSA", "stock"),
    ]),
    ("Commodities", [
        ("GLD", "GLD", "stock"),
        ("SLV", "SLV", "stock"),
        ("GDX", "GDX", "stock"),
        ("USO", "USO", "stock"),
        ("UNG", "UNG", "stock"),
        ("CPER", "CPER", "stock"),
        ("DBA", "DBA", "stock"),
    ]),
    ("Currency ETFs", [
        ("UUP", "UUP", "stock"),
        ("FXE", "FXE", "stock"),
        ("FXY", "FXY", "stock"),
        ("FXB", "FXB", "stock"),
    ]),
    ("Volatility", [
        ("VIXY", "VIXY", "stock"),
    ]),
]
